name: Node.js Package

on:
  release:
    types: [created]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check version numbers
        run: |
             chmod +x ./bin/validate-version.sh
             ./bin/validate-version.sh
        shell: bash

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/iron
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  publish-npm:
    needs:
      - check-version
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/iron
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Build package
        run: |
             chmod +x ./bin/build-release.sh
             ./bin/build-release.sh
        shell: bash
      - name: Publish to npm
        run: cd package && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
