name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check version numbers
        run: ./bin/validate-version.sh

  publish-npm:
    needs:
      - build
      - check-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci
      - name: Build package
        run: ./bin/build-release.sh
      - name: Publish to npm
        run: npm publish --workspace=package
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
